export const APP_CONSTANTS = {
    code: {
        status_internal_server: 500,
        status_success_code: 200,
        status_badrequest_code: 400,
        status_unauthorize_code: 401,
        status_exist_code: 403,
        status_notfound_code: 404,
        status_notdatafound_code: 404,
        status_bad_gateway: 502,
        TOO_MANY_REQUESTS: 429,
        SERVICE_UNAVAILABLE: 503,
    },
    constword:{
         password :"password",
         new_password:"new_password",
         channelID:"channel_id",
         profile:"profile",
         images:"images",
         userLocation:"userLocation",
         preference:"preference",
         message:"message",
         self:"self",
         partner:"partner",
         LOWER:"LOWER",
         User:"User",
         Match:"Match"
    },
    type:{
      user:'user',
      admin:'admin'
    },
    error:{
        redis_client_conn:"Redis client is not open. Ensure server initialized the client",
        send_msg:"Unable to send message: User is blocked",
        like_con:"LikeController Error",
        respond_con:"respondToLike error:",
        radar:"Radar returned match without valid user_id, fetching using profile_id",
        skip_profile:"Profile not found for profile_id → skip",
        user_skip:"Profile has no user_id → skip",
        no_match:"No matches with valid user_id found after DB lookups",
        radar_err:"Radar external API error",
        skip_filter:"Skipping match with invalid user_id:",
        user_match:"Error filtering match for user",
        gemini_key_err:"GEMINI_API_KEY environment variable is not set'",
        chan_pub:"Failed to publish message:",
        external_fail:"`External sync failed:",
        likecontroller_likeErr:"LikeController.likeProfile",
        likecontroller_dislikeErr:"LikeController.dislikeProfile",
        likecontroller_res_accept:"LikeController.respondToLike",
        likecontroller_res_reject:"LikeController.getLikedProfiles",
        chatcontroller_send_msg:"ChatController.sendMessage",
        chatcontroller_get_history:"ChatController.getChatHistory",
        chatcontroller_getchatList:"ChatController.getChatList",
        user_toggle_block:"ChatController.toggleBlockUser",
        report_user:"ChatController.reportUser",
        ai_suggestion:"ChatController.getAISuggestions",
        profilecontroller_err:"profileController error",
        ai_initial_suggestion:"ChatController.getInitialAISuggestions",
        subscribe_channel:"ChatController.subscribeToChannel",
        sse_err:"Error ending SSE response:",
        image_url:"Image URL sign error:",
        get_url:"Error generating signed URL:",
        match_for_chat:"Repository Error - verifyCanChat:",
        get_preference:"ProfileRepository.getPreferencesByUserId error:",
        sequalize_err:"SequelizeUniqueConstraintError",
        channel_issue:"Failed to subscribe to channel",
        send_chan:"Failed to send error to client:",
        signin :"Siginin error check the credentails",
        reset_password_issue:"check the passwords ",
        upload_profile_issue:"upload_profile_issue",
        is_user_blocked:"Error in isUserBlocked:",
        is_like_already:"Error in isAlreadyLiked:",
        is_reject_already:"Error in isAlreadyRejected:",
        has_report:"Error in hasReportedUser:",
        disliked:"Error in isAlreadyDisliked:",
        getchannel:"Error in getChannelInfo:",
        blocked_channel:"Error checking block status:",
        send_message:"You blocked this user. Unblock to send messages.",
        gemini_service_Err:"AIService Error - generateSuggestions:",
        failed_search_chat:"failed to search in chat",
        archiveChat:"Error in archiveChat controller",
        unarchiveChat:"Error in unarchiveChat controller",
        getArchivedChat:"Error in getArchivedChats controller",
        delete_message:"Failed to delete messages",
        total_count_fetch:"Failed to fetch total chat count:",
        notification_fetch:"Error fetching notifications",
        mark_seen:"Error marking notification as seen",
        all_message_mark_seen:"Error marking all notifications as seen",
        unread_count:"Error fetching unread count",
        notification_id:"Notification ID is required",
        notification_not_found:"Notification not found",
        already_seen:"Notification already marked as seen",
        unread_message:"Error fetching unread messages:",
        refreshToken_error:"refreshToken error:"
    },
    number:{
      zero:0,
      one:1,
      ten:10,
      hundred : 100
    },
    action:{
          pending:"pending",
          accept:"accept",
          accepted:"accepted",
          rejected:"rejected",
          reject:"reject",
          disliked:"disliked",
          connection:"connection",
          blocked:"blocked",
          ai_suggestions:"ai_suggestions",
          read_receipt:"read_receipt",
          unblocked:"unblocked",
          error:"error",
          active:"active",
          inactive:"inactive",
          all:"all",
          is_delete:"is_deleted",
          reported:"reported",
          user:"user",
          admin:"admin",
          true:"true",
    },
    message: {
        something_went_wrong: "Something went wrong",
        chat_history:"Chat history must be an array",
        chat_sugg:"Each chat entry must have speaker and message",
        error_in_findLikedprofiles: "Error in findLikedprofiles",
        error_in_likeProfile: "Error in likeProfile",
        error_in_findDislikedprofiles: "Error in findDislikedprofiles",
        error_in_dislikeProfile: "Error in dislikeProfile",
        error_in_createMatch: "Error in createMatch",
        refresh_failed:"Token refresh failed",
        token_refreshed:"Token refreshed successfully",
        chan_req:"Channel ID is required",
        chat_not_found:"Chat not found",
        marked_as_seen :"Notification marked as seen",
        error_in_getrequestProfiles: "Error in getrequestProfiles",
        error_in_getMatchedProfiles: "Error in getMatchedProfiles",
        error_in_rejectLike: "Error in rejectLike",
        notification:"You have a new message",
        invalid_channel:"Invalid channel or partner not found",
        affinity_hobbies_fetched_successfully: "Affinity hobbies fetched successfully",
        signin_failed: "phone_number and country_code are required",
        token_required: "Authentication token is required",
        token_expired: "Token has expired",
        failed_create:"Failed to create account",
        invalid_token: "Invalid token",
        not_otp_verification:"not_otp_verification",
        unauthorized_user: "Unauthorized user",
        register_user_failed: "phone_number and country_code are required",
        mobile_validation_message: "Phone number must be exactly 10 digits for +91",
        exist_user_check: "Phone number is already registered",
        registeration_success: "Registration successful",
        not_register_user: "Phone number is not registered. Please register first.",
        user_not_found: "User not found",
        signin_success: "Signin successful",
        database_user_check_error: "Database error while checking user",
        failed_get_user_error: "Failed to create or fetch user",
        affinity_political_beliefs_fetched_successfully: "Affinity political beliefs fetched successfully",
        affinity_religion_fetched_successfully: "Affinity religion fetched successfully",
        affinity_ethnicity_fetched_successfully: "Affinity ethnicity fetched successfully",
        admin_register_success: "Admin registered successfully",
        password_not_match: "Password doesn't match",
        email_exist: "Email already exist",
        admin_create_success: "Admin created successfully",
        login_success: "Logged in successfully",
        invalid_credential: "Invalid Credentials",
        email_not_register: "Email not registered",
        role_created: "Role created successfully",
        role_not_created: "Role not created",
        role_name_exist: "Role name already exist",
        permissions_fetched: "Permissions fetched successfully",
        permission_not_found: "Permissions not found",
        permisson_assigned: "Permissions assinged successfully",
        dashboard_data_fetched: "Dashboard data fetched",
        data_fetched: "Data fetched",
        role_updated: "Role updated",
        role_not_found: "role not found",
        role_deleted: "Role deleted successfully",
        role_cant_delete: "Role is assigned to user. Cant delete",
        profile_fetch_success: "Profile fetched successfully",
        no_duplicate: "No updatable fields provided",
        dob_format_skip: "Invalid DOB format, skipping age calculation",
        profile_update_success: "Profile updated successfully",
        location_update: "Location updated successfully",
        field_update: "Field updated successfully",
        profile_field_empty: "No profile setup fields provided",
        profile_setup_saved: "Profile setup saved successfully",
        verification: "Please verify your profile before searching for matches",
        password_reset: "Password reset token generated",
        password_update: "Password updated successfully",
        admin_creation_limit_reached: "Admin creation limit reached (maximum 5 allowed).",
        otp_message_email: "An OTP  has been sent to your Email",
        otp_message_mobile: "An OTP  has been sent to your Mobile Number",
        otp_sent: "OTP sent successfully",
        otp_verified: "OTP verified",
        verify_otp: "Please verify otp",
        invalid_otp: "Invalid OTP",
        otp_expired: "OTP has expired",
        profile_not_found:"Profile not found",
        otp_required:"User ID and OTP are required",
        password_update_success: "Password updated successfully",
        email_does_not_exist: "Email does not exist",
        user_updated :"User updated successfully",
        register_validation:"Email or phone required",
        setup_password:"user_id,Password and confirm_password are required",
        password_notmatch:"Passwords do not match",
        password_already_set:"Password already set",
        notification_message: "Notification triggered",
        password_reset_otp_sent: "Password reset OTP has been sent to your email",
        failed_create_temp: 'Failed to create pending registration',
        failed_delete_temp: 'Failed to clean up pending registration',
        failed_create_user: 'Failed to create user account',
        database_error: 'Database operation failed',
        temp_user_not_found: 'No pending registration found',
        forgot_password:"Can you check your email",  
        temp_register:"Pasword already set",
        no_file:"No files uploaded",
        dob_verify:"Invalid date format. Please use YYYY-MM-DD format",
        temp_not_found:"Temp user not found",
        validation_error:"Validation error",
        encrypted_pass:"Reset password decryption failed or not encrypted; using raw values",
        send_message_req:"partnerId and message are required",
        unauthorized:"unauthorized",
        blocked_user_id:"blockedUserId is required",
        blocked_success:"User blocked successfully",
        report_msg:"reportedUserId and reason are required",
        report_success:"Report submitted",
        chat_report_error:"ChatController reportUser Error",
        chat_controller:"ChatController Error",
        liked_id_req:"likedId is required",
        like_error:"Cannot like your own profile",
        like_chat:"LikeController Error",
        liked_action_req:"likedId and action are required",
        invalid_action:"Invalid action. Must be either 'accept' or 'reject'",
        invalid_request:"Invalid request",
        no_pending_request:"No pending like request found.",
        request_declined:"Request declined",
        going_to_chat:"You accepted the request. Chat activated",
        preference_controller:"PreferenceController Error",
        field_value:"field and value are required",
        liked_user_not_found: "Liked user not found",
        disliked_user_not_found: "Disliked user not found",
        error_checking_like_status: "Error checking like status",
        error_creating_like: "Error creating like",
        error_checking_mutual_like: "Error checking mutual like",
        you_liked_this_profile: "You liked this profile",
        you_disliked_this_profile: "You disliked this profile",
        already_disliked: "User already disliked",
        match_successful: "Match successful!",
        error_creating_match: "Error creating match",
        error_rejecting_like: "Error rejecting like request",
        error_accepting_like: "Error accepting like request",
        already_liked: "Already liked",
        phone_number_already_registered: "Phone number is already registered with another account",
        age_min_greater_than_max: "age_min must be less than or equal to age_max",
        height_min_greater_than_max: "height_min_cm must be less than or equal to height_max_cm",
        preferences_saved_successfully: "Preferences saved successfully",
        preferences_fetched_successfully: "Preferences fetched successfully",
        preferences_not_found: "User preferences not found. Please set preferences first.",
        users_filtered_successfully: "Users filtered successfully",
        preference_updated_successfully: "Preference updated successfully",
        failed_send_message: "Failed to send message",
        failed_fetch_chat_history: "Failed to fetch chat history",
        failed_fetch_chat_list: "Failed to fetch chat list",
        failed_fetch_chat_partners: "Failed to fetch chat partners",
        failed_mark_messages_read: "Error marking messages as read",
        failed_block_user: "Failed to block user",
        failed_report_user: "Failed to report user",
        redis_subscription_failed: "Chat subscription failed. Please try again.",
        redis_subscriber_connection_failed: "Failed to establish Redis subscriber connection",
        redis_connection_unavailable: "Redis connection unavailable",
        missing_email_params: "Missing required email parameters (to, subject, text)",
        invalid_recipient_email: "Invalid recipient email address",
        smtp_verification_failed: "SMTP connection verification failed",
        email_sent_successfully: "Email sent successfully",
        failed_send_email: "Failed to send email",
        missing_template_params: "Missing required template email parameters (to, subject, templatePath)",
        template_file_not_found: "Template file not found",
        failed_render_template: "Failed to render template",
        failed_send_template_email: "Failed to send template email",
        only_matched_can_chat: "Only matched profiles can chat",
        user_blocked: "User is blocked or blocked you",
        user_unblocked_success: "User unblocked successfully",
        unblock_failed: "Failed to unblock user",
        no_like_request_found: "No like request found from this user",
        ai_chat_success:"AI suggestions generated successfully",
        initial_ai_Chat_success:"Initial AI suggestions generated successfully",
        password_updated_successfully:"Password updated successfully",
        admin_not_found_or_no_changes:"Admin not found or no changes made",
        user_fetched: "user fetched",
        database_error_occurred:"Database error occurred",
        invalid_password_decryption: "Invalid password decryption!",
        helpandsupportmessage: "Got it! Our team will get back to you",
        failed_fetch_profile:"Failed to fetch profile",
        failed_to_update:"'Failed to upsert profile",
        failed_to_update_image:"Failed to update images",
        failed_to_update_location:"Failed to upsert location ",
        self_message:"Cannot send message to yourself",
        not_matched:"cant chat ,Chat not enabled",
        chat_message_req:"Either roomId or receiverId must be provided",
        failed_to_join_chat:"Failed to create or join room",
        room_id_req:"Room ID is required",
        roomt_not_found:"Room not found",
        invalid_error:"Invalid userId or partnerId",
        exist_channel:"existing_channel",
        no_chan:"no_channel_found",
        ai_chat_error:"Failed to generate AI suggestions. Please try again",
        target_req:"Target user ID is required",
        connected_chan:"Connected to channel",
        image_update_failed:"Image update failed",
        reports_fetched: "Reports fetched",
        invalid_password_encryption: "Invalid password encryption!",
        failed_to_fetch_reports:"Failed to fetch reports",
        role_not_assigned:"Role not assigned to this admin",
        invalid_role_assigned:"Invalid role assigned",
        account_del:"Account deleted successfully.",
        account_permanently_deleted: "Account permanently deleted after recovery period",
        create_newone:"Account deleted but recreate window passed. You can create new one.",
        your_account_deleted:"Your account was deleted",
        title_and_message_required:"Title and message are required",
        trigger_to_required_and_must_string:"trigger_to is required and must be a string",
        Invalid_trigger_to_Allowed_values:"Invalid trigger_to. Allowed values: 'active', 'inactive', 'all'",
        Notifications_processed_successfully:"Notifications processed successfully",
        File_too_large:"File too large. Maximum size is 5MB.",
        DB_error_AdminRepository_getUsersList:"DB error in AdminRepository.getUsersList:",
        File_upload_failed_during_processing:"File upload failed during processing",
        you_blocked:"You blocked this user",
        your_blocked_by:"You are blocked by this user",
        phone_number_already_verified:"phone_number_already_verified",
        search_err:"Error searching chat list",
        already_Verified:"This phone number is already verified. You cannot verify it again.",
        dont_verify_mobile:"Cannot change phone number during verification. Use your existing phone or contact support.",
        self_like:"You cannot like yourself",
        Failed_to_fetch_dashboard_data:'Failed to fetch dashboard data',
        get_help_support_err:"get help and support error:",
        get_report_user_err:"get_report user error",
        fetch_error:"Error fetching filter list:",
        notification_err:"Error fetching admin notifications:",
        data_fetch:"Data fetched",
        report_err:"Error fetching reports:",
        help_and_support:"Error in Help and Support",
        fetch_success:"Dashboard data fetched successfully",
        filter_err:"Error in getFilterList:",
        get_notification:"Error in getNotificationList:",
        notification_send_success:"Successfully sent message",
        notification_error:"Error sending message:",
        Socket_IO_not_initialized:"Socket.IO not initialized",
        archived_success:"Chat archived successfully",
        unarchived_Success:"Chat unarchived successfully",
        getarchived_status:"Archived chats retrieved successfully",
        selected_message:"Selected messages deleted successfully",
        clearchat:"Chat cleared successfully",
        chat_removed:"Chat removed successfully",
        reason:"User archived this conversation",
        is_archived:"Failed to mark chat history as archived",
        is_unarchived:"Failed to mark chat history as unarchived",
        invalid_file_type:"Invalid file type",
        No_files_provided_in_upload_profilerequest:"No files provided in upload profile request",
        admin_not_found:"Admin not found",
        admin_deleted_successfully:"Admin deleted successfully",
        admin_delete:"Your account is deleted by admin",
        err_delete:"Error in deleteUser:",
        undelete:"User restored successfully",
        restore_err:"Error in restoreUser:",
        cant_chat:"You cannot send messages because this conversation is blocked",
        Filter_parameter_required:"Filter parameter is required",
        Invalid_filter_type:"Invalid filter type",
        account_delete_sub:"Account Deletion Notification",
        account_delete_msg:"Your account has been deleted by admin as per our policy.",
        image_req:"Both selfie URL and profile image URLs are required",
        face_verification_failed:"Face verification failed",
        try_again:"Face verification service failed. Please try again.",
        selfie_image :"Selfie image URL is required",
        profile_found:"User profile not found",
        image_not_found:"No profile images found. Please upload profile images first",
        face_verification_success:"Face verification successful",
        face_verify_score:"Face verification score below threshold",
        Signed_url:"Signed URL error:",
        gupshup_failed:"Failed to send OTP via Gupshup",
        failed_to_send_otp:"Failed to send OTP",
        email_and_otp_req:"Email and OTP are required"
        
    },
    socket_fields: {
        userUnblocked:"userUnblocked",
        userBlocked:"userBlocked",
        likeCreated:"likeCreated",
        helpSupportCreated:"helpSupportCreated",
        userCreated:"userCreated",
        userReported:"userReported",
        matchCreated:"matchCreated",
        userStatusUpdated:"userStatusUpdated",
        userDeleted:"userDeleted",
        adminCreated:"adminCreated",
        roleCreated:"roleCreated"
    }
}

export const MASTER_KEYS = {
    EDUCATION: 'education',
    RELATIONSHIP: 'relationship',
    LOOKING_FOR: 'looking_for',
    FAMILY_CHILDREN_HAVE: 'family_children_have',
    FAMILY_CHILDREN_WANT: 'family_children_want',
    HABIT: 'habit',
    HOBBY: 'hobby',
    POLITICAL_BELIEF: 'political_belief',
    ETHNICITY: 'ethnicity',
    RELIGION: 'religion',
    LANGUAGE: 'language',
};

export const USER_FIELDS = {
    ID:'id',
    USER_ID: 'user_id',
    IS_ACTIVE: 'is_active',
    DEVICE_TOKEN: 'device_token',
};

export const NOTIFICATION_FIELDS = {
    ID: 'id',
    SENDER_ID: 'sender_id',
    RECEIVER_ID: 'receiver_id',
    MESSAGE: 'message',
    NOTIFICATION_TYPE: 'notification_type',
    IS_SEEN: 'is_seen',
    CREATED_AT: 'created_at',
    DESC:'DESC',
    NOTIFICATION_TITLE: 'notification_title',
    NOTIFICATION_MESSAGE: 'notification_message',
    TRIGGER_TO: 'trigger_to',
    CITY: 'city',
    STATE: 'state',
    CREATED_AT_CAMEL: 'createdAt',
    COUNT:"COUNT",
    DISTINCT:"DISTINCT",
    distinct_senders:"distinct_senders"
};

export const ADMIN_FIELDS = {
    ID: 'id',
    FULL_NAME: 'full_name',
    EMAIL: 'email',
    PHONE_NUMBER:'phone_number',
    COUNTRY_CODE:'country_code',
    IS_MOBILE_VERIFICATION:'is_mobile_verification',
    PASSWORD: 'password',
    ROLE_ID: 'role_id',
    IS_ACTIVE: 'is_active',
    OTP: 'otp',
    OTP_EXPIRE_TIME: 'otp_expire_time',
    IS_ACCOUNT_OWNER: 'is_account_owner',
    CREATED_AT_CAMEL: 'createdAt',
    CREATED_AT: 'createdAt',
};

export const GEMINI_API_ERROR_CHECK ={
  RESOURCE_EXHAUSTED:"RESOURCE_EXHAUSTED",
  quota:"quota",
  not_found:"not found",
  service:"Service Unavailable",
  overloaded:"overloaded",
  gemini2_0:"gemini-2.0-flash",
  gemini2_5:"gemini-2.5-flash"
}

export const USER_EXTRA_FIELDS = {
    ID: 'id',
    PASSWORD_HASH: 'password_hash',
    USERLOCATION:"user_location",
    OTP: 'otp',
    OTP_EXPIRES_AT: 'otp_expires_at',
    CREATED_AT: 'created_at',
    DESC: 'DESC',
    USER_PROFILE_ID:'user_profile_id',
    LIKED_PROFILE_ID:'liked_profile_id',
    STATUS:'status'
};

//chat constant 
export const CHAT_HISTORY = {
  ID: 'id',
  CHAT_MSG: 'chat_message',
  CREATED_AT: 'created_at',
  CHANNAL_ID: 'channel_id',
  SENDERID: 'sender_id',
  RECEIVERID: 'receiver_id',
  IS_READ: 'is_read',
  IS_ARCHIVED:'is_archived',
  DELETED_FOR_USERS:'deleted_for_users',
  ARCHIVED_FOR_USERS:'archived_for_users',
  DESC:'DESC',
  USER1: 'user1',
  USER2: 'user2',
  LEAST:"LEAST",
  GREATEST:"GREATEST",
  MAX:"MAX",
  IF:"IF",
  CONCAT:"CONCAT",
  has_message:"has_message"
}

//user location
export const USERLOCATION = {
  LATITUDE: 'latitude',
  LONGITUDE: 'longitude',
  CITY: 'city',
  STATE: 'state',
  COUNTRY: 'country'
}

//User image 
export const USERIMAGE = {
  ID: 'id',
  IMAGE_URL: 'image_url',
  IS_PROFILE_PIC: 'is_profile_pic',
  ORDER_INDEX: 'order_index'
}
// constants.ts

export const PROFILE_FIELDS = {
  // Mandatory Profile Fields
  MANDATORY: {
    FIRST_NAME: 'first_name',
    LAST_NAME: 'last_name',
    DOB: 'dob',
    AGE: 'age',
    HEIGHT: 'height',
    GENDER: 'gender',
    LOCATION: 'location',
    PROFILE_IMAGE: 'profile_image',
    IMAGE_URL:'image_url',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    CITY:'city',
    STATE:'state',
    ASC:'ASC'
  },

  // Preference Fields (User's dating preferences)
  PREFERENCES: {
    GENDER: 'gender',
    AGE_MIN: 'age_min',
    AGE_MAX: 'age_max',
    LOCATION_RADIUS_KM: 'location_radius_km',
    LANGUAGES: 'languages',
    HEIGHT_MIN_CM: 'height_min_cm',
    HEIGHT_MAX_CM: 'height_max_cm',
    RELIGION: 'religion',
    EDUCATION_LEVEL: 'education_level',
    ETHNICITY: 'ethnicity',
  },
  // Optional / Additional Profile Fields
  OPTIONAL: {
    EDUCATION: 'education',
    WORK_PLACE: 'work_place',
    JOB_TITLE: 'job_title',
    ORIENTATION: 'orientation',
    RELATIONSHIP_TYPE: 'relationship_type',
    LOOKING_FOR_GENDER: 'looking_for_gender',
    LOOKING_FOR_INTENTION: 'looking_for_intention',
    ETHNICITY: 'ethnicity',
    HOMETOWN: 'hometown',
    POLITICAL_BELIEFS: 'political_beliefs',
    DRINK: 'drink',
    SMOKE: 'smoke',
    HOBBIES: 'hobbies',
    INTERESTS: 'interests',
    LANGUAGES: 'languages',
    EDUCATION_LEVEL: 'education_level',
    USER:'User',
    PROFILE : 'profile',
    PROFILE_ID: 'profile_id',
    LOWER: 'LOWER',
  },

  // Verification & Image Keys
  VERIFICATION: {
    PHONE_VERIFICATION: 'phone_verification',
    PROFILE_VERIFICATION: 'profile_verification',
  },

  IMAGES: {
    ADD_MORE_IMAGES: 'add_more_images', // will be used dynamically
  }
};
export const UPSERT_MATCH_MAKING = 'http://65.2.167.107:8000/v1/users/upsert'
export const RADAR_FIND_MATCH = "http://65.2.167.107:8000/v1/users/radar"

// src/config/constants.ts  (or wherever you keep your constants)
export const DEFAULT_CONFIG = {
  JWT_SECRET: 'affinity_local_key',
  EXPIRY_TIME: '1d', 
  REFRESH_EXPIRY:"60d",  
  ENCRYPT_KEY:"test",
  SOMEONE:"Someone",
  NEW_MESSAGE:"You have a new message",
  NEW_NOTIFICATION:"New Notification",
  CONNECTION_ACCEPTED:"Connection Accepted",
  NEW_LIKE:"New Like",
  REFRESH_SECRET:"affinity_local_key_refresh"
}

export const FILTER_MATCH_CHECK ={
  USERPROFILEID:"userProfileId",
  LIKEDPROFILEID:"likedProfileId",
  STATUS:"status",
  BLOCKEDUSERID:"blocked_user_id",
  USERID:"user_id",
  REPORTEDUSERID:"reported_user_id"

}
export const  twoWeeks = 14 * 24 * 60 * 60 * 1000;
export  const MAX_FILE_SIZE = 5 * 1024 * 1024;

// User Filter Constants
export const USER_FILTERS = {
  MATCHED_PROFILE: 'matchedprofile',
  LIKED_PROFILE: 'likedProfile',
  DISLIKE_PROFILE: 'dislikeProfile',
  BLOCKED_USER: 'BlockedUser',
};

// User Association Constants
export const USER_ASSOCIATIONS = {
  LIKER: 'liker',
  LIKED: 'liked',
  BLOCKER: 'blocker',
  BLOCKED: 'blocked',
  REPORTER: 'reporter',
  REPORTED: 'reported',
  USER: 'user',
}; 
